version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - bash infra/pipeline/install-terraform.sh
  build:
    commands:
      - bash infra/pipeline/plan.sh
artifacts:
  files:
    - 'package.json'
    - 'dist/**/*'
    - 'infra/**/*'
    - 'infra/**/.terraform.lock.hcl'
  exclude-paths:
    - 'infra/**/.terraform/**/*'
    - 'infra/**/*.tfstate*'
    - 'infra/**/*.tfvars*'
  discard-paths: no
